#!/usr/bin/env bash
# The script aims to display information about subdomains for a given domain.

extract() {
	local domain=$1
	local sub=$2
	ip=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tail -1)
	rec=$(dig "$sub"."$domain" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tail -1)
	echo "The subdomain $sub is a $rec record and points to $ip"
}
if [ $# -eq 2 ]; then
	extract "$1" "$2"
else
	extract "$1" 'www'
	extract "$1" 'lb-01'
	extract "$1" 'web-01'
	extract "$1" 'web-02'
fi
