#!/usr/bin/env bash
# configure Nginx to listening on port 80.

sudo service nginx stop

sudo sed -i 's/listen [^;]*/listen 80/' /etc/nginx/sites-available/default

sudo service nginx start

# another way to do it : sudo rm /etc/nginx/sites-enabled/default
# sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
