#!/usr/bin/env bash
# a Bash script

trap high_2 SIGTERM
trap high_3 SIGINT
trap high_1 SIGQUIT

high_1()
{
  rm -rf /var/run/myscript.pid
  exit
}

high_2()
{
  echo "I hate the kill command"
  high_1
}

high_3()
{
  echo "Y U no love me?!"
}

echo $$ > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
