#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinitely
# receives any signal is called `trap`.
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
