#!/usr/bin/env bash
# loops from 1 to 10, displays bad luck for the 4th iteration, good luck for the 8th loop iteration, Best School for the other iterations

((a = 0))
while (( a < 10 ))
do
	((a += 1))
	if [ "$a" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$a" -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
