#!/usr/bin/env bash
# install ufw firewall
sudo apt-get update
sudo apt-get install -y ufw 

# a good way to set some defaults
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow ports
sudo allow ufw 22/tcp
sudo allow ufw 443/tcp
sudo allow ufw 80/tcp

sudo ufw enable
